version: "3.9"

services:
  db:
    container_name: forum-db
    image: postgres:14-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - .env
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_SERVER=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - forum

  api:
    build: .
    container_name: forum-api
    restart: always
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - forum

  redis:
    container_name: forum-cache
    image: redis:7.2.1-alpine3.18
    ports:
      - "6379:6379"
    volumes:
      - './data/redisdata:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - forum

networks:
  forum:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local